Updated docs to include proxy instructions
OctopusDeploy/OctopusGrafanaDataSource pull request #2
Opened 2022-11-03 23:48 UTC by mcasperson

2022-11-03 23:53 UTC, FinnianDempsey approved these changes

2022-11-03 23:54 UTC, FinnianDempsey approved these changes

2022-11-04 00:03 UTC, FinnianDempsey requested changes
They'll also need to add the host to resolve it which I believe can't be done during a docker build. 

Suggest adding a command with --add-host like:
`docker run -d -p 3000:3000 --name=grafana --add-host=octo.domain.local:192.168.0.232 custom_grafana_image`

2022-11-04 00:36 UTC, jbristowe approved these changes

2022-11-06 23:53 UTC, merged